### ISSUE TITLE
Not fully saving after work

### ISSUE THREAD

**Issue by ghost** [H4lo/Away_From_Sub_Function_IN_IDA#1]
Hi

Your script not fully save `func_name`

![image](https://user-images.githubusercontent.com/8020186/207160094-2c565164-dba9-4758-abc3-017a4035a269.png)

**Comment by H4lo** [comment]
You need to manually press F5 in the code to regenerate the pseudocode, I don't know if there is a suitable idapython function that can refresh the display of function symbols..
